### ISSUE TITLE
Hot-reloading not working with Docker+Dash

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1218]
I'm not sure if we can actually make this functionality worth it. It seems like we'd need to get hot reloading to work through three different layers: docker, gunicorn, and dash.

Alternatively, we can try invoking the python file directly (which allows us to avoid docker and gunicorn), as @joshuayhwu described:

> P.s: For instant updates, a way to get around it is to do the following: 0) add import sys and sys.path.append('../') at top of the file 1) specify app=Dash(__name__) at the top of the file, 2) set app.layout= html.Div for the layout part 3)add if__name__ == ‘__main__': app.runsever(debug=True) 4) run the python file inside server/dash directory by calling py <filename>.py

It might be easiest to get our dashboards set up with the changes mentioned above for local development, and deploy with our existing Docker setup.

**Comment by joshuayhwu** [comment]
Slack has some problems with typing literal underscores, so I will repeat the steps below:

0)  Add  the following code block at the top of the file - this is necessary as you need the color configs from parent directory
```import sys ```

``` sys.path.append('../')``` 
 
1)  Specify the following at the top of the file  - for the dash app to run locally
 ```app=Dash(__name__)``` 

2) Replace layout variable with the following:
``` app.layout = html.Div([... ```

3) Add the following line on the bottom of the file:
``` if __name__ == '__main__': ```
``` app.runserver(debug=True) ```

4) Run the Python file inside the server/dash directory
``` python <filename>.py```

For the possible hot-reloading feature, this might be helpful: https://medium.com/hootsuite-engineering/hot-reloading-on-a-dockerized-flask-app-4e87b88ea303

But I am not sure if the hot reloading will be fast enough to make the feature useful

**Comment by joshuayhwu** [comment]
Since I don't understand how gunicorn works, I am making my assumptions based on my understanding on docker and dash.

Dash would automatically enable hot reload if debug=True (as in the code). Docker should allow this functionality process within the container as long as we mount the current working directory to the volume, which essentially is a file-sharing system between current directory and the container. 

The [docmentation](https://github.com/hackforla/311-data/blob/dev/server/dash/dashboards/README.md) instruction includes the mounting part (the "-v" part in docker run), but somehow hot reloading doesn't not work. For reference, check [here](https://stackoverflow.com/questions/44342741/auto-reloading-flask-server-on-docker), [here,](https://medium.com/hootsuite-engineering/hot-reloading-on-a-dockerized-flask-app-4e87b88ea303) and [here](https://gist.github.com/up1/5f47d1f7ec3083c8ea12ae9bf39bcc35) 

Even though automatic hot-reload doesn't work yet, it seems like semi-hot-reload works in this case. When an update is made, simply stop the container and rerun the container. These updates should be reflected now.

**Comment by nichhk** [comment]
Josh and I discussed this offline, and he stated that stopping/rerunning the container takes 2-4 minutes. This is pretty slow, so I tried avoiding Docker and just using gunicorn+dash. If we simply provide `--reload` to the gunicorn command, we can get hot-reloading to work. The developer does need to manually hit the refresh button, but I feel this is an acceptable workaround. I'll work on updating the documentation.
