### ISSUE TITLE
Develop a 311 request forecasting model

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1289]
### Overview
It would be interesting to see whether we can accurately forecast the number of created 311 requests for a future date.

### Action Items
- [ ] Train a basic forecasting model.

**Comment by nichhk** [comment]
@susanklm: Could you write a comment here describing what you've tried, what the results were, and next steps, if any?

**Comment by susanklm** [comment]
For the 311-data time series analysis, I used Auto Arima to make monthly forecast of the 311 requests number and Facebook Prophet to make daily forecast of the 311 requests number. Both Auto Aurima and Prophet gave a decent forecast. 

Root Mean Square Error (RMSE) of the Auto Arima is 14,808.68. This tells us that our model was capable of forecast the average monthly total request in the test set within 14,808.68 of the actual total request. Our month by month total requests range from around 552 to over 23,266. So, it seems the model is not that bad, but not good either.

Similarly, the RMSE of the Prophet is 788.91. This means that our model was capable of forecast the average daily total request in the test set within 788.91 of the actual total request. Our day to day total requests range from around 2 to over 5,073. So, it seems the model is pretty decent.

To make a better predition of the requests number, probably we can try different time forecasting library instead of Auto Arima and Prophet. Also, maybe we can add some features to make the model adapts to the decresing trend that we see since early 2021 (see Monthly Forecast's sesonal_decompose).

Here are the links to the Jupyter Notebook:
* [Monthly Forecast](https://github.com/susanklm/MyLA311_Service_Request-Time_Series_Analysis/blob/main/LA311_16_21_analysis_monthly.ipynb)
* [Daily Forecast](https://github.com/susanklm/MyLA311_Service_Request-Time_Series_Analysis/blob/main/LA311_16_21_analysis_daily.ipynb)

Here are the links to the exploratory analysis on 2020 dataset and 2016 - 2021 dataset using Tableau:
* [311-Data 2020 EDA](https://public.tableau.com/app/profile/susan.kolim/viz/MyLA3112020Analysis/MonthlyRequestsbyRegion?publish=yes)
* [311-Data 2016-2021 EDA](https://public.tableau.com/app/profile/susan.kolim/viz/My3112016-2021/MonthlyRequests2016-2021?publish=yes)

**Comment by susanklm** [comment]
For the time being, I am not sure how to improve the model. Therefore, I won't continue working with this project anymore.
