### ISSUE TITLE
Implement desktop menu redesign

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1370]
### Overview
Our designers have redesigned the desktop menu design in #1157, so we need a frontend engineer to implement it.

### Action Items
- [ ] Take a look at the [figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1009%3A1004) and implement the changes

### Resources/Instructions
This fits in nicely with Edwin's work on switching to a light theme in #1362, so Edwin has agreed to take a look at it.

- https://github.com/hackforla/311-data/issues/1396

**Comment by edwinjue** [comment]
@melissahermes99 @elizabeth-ux 
I was taking a look at the final v2 design for the desktop menu in [figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=5711%3A20866) and noticed the dimensions  for the new design are `417x838px`. 

Although taken from a high resolution display, as you can see from the screenshots, the new dimensions you propose may take up quite a bit of real estate on the screen especially for those on lower resolution displays.

Before I do any more work on this, I would like to confirm the new dimensions for the desktop menu is what you want because these new dimensions will require a new v2 design specification for the calendar picker as well considering the increased width of the new design will make the existing calendar picker look small by comparison to the rest of the desktop menu items and won't maximize on the new real estate presented by increasing width from `325px` to `417px`

Please let me know what you decide. I will be putting this on hold until I hear back. Thanks! 

### NEW DESIGN - desktop menu (`417x838px`) - [figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=5711%3A20866)
![image](https://user-images.githubusercontent.com/1448719/193424879-7c303333-e78d-482e-8879-25a836952bde.png)
![image](https://user-images.githubusercontent.com/1448719/193425015-cc6bcc64-72a1-46a9-89f7-ce249a6d59c7.png)
![image](https://user-images.githubusercontent.com/1448719/193425036-fdc86d4b-e21b-456d-a0fd-12c695ee924a.png)


### CURRENT DESIGN - desktop menu (`325x488px`) - current development
![image](https://user-images.githubusercontent.com/1448719/193424928-99b49181-d78d-460c-9c1d-ef36a282fed8.png)
![image](https://user-images.githubusercontent.com/1448719/193424983-552c09b6-08d6-4f8b-ba37-c9f2a0a60168.png)
![image](https://user-images.githubusercontent.com/1448719/193424975-aa296e05-0ed0-4da4-939e-d6b31bd099dd.png)

**Comment by melissahermes99** [comment]
I definitely see what you mean, it does take up a lot of space. I much prefer the current design that's in development's dimensions. I am not entirely sure what happened here because I do not think it was the intention to make it that large, going back to our Design Studio page, the previous dimensions of our map menu should've been smaller. I think what might've happened was that while Elizabeth and I were working on it, we scaled it up for visibility while designing and never came back to adjust it again. The map will be a little longer now that we're including a boundaries option but that's about it. I've adjusted the design again in Figma and I will double-check this with Elizabeth! Thanks a ton for letting me know.

**Comment by edwinjue** [comment]
Thanks for the quick response @melissahermes99 and for adjusting the design. I will continue to work in the original dimensions and focus on small changes until you check in and confirm with Elizabeth.

**Comment by melissahermes99** [comment]
@edwinjue Elizabeth has confirmed that it looks right and everything is good to go!

**Comment by edwinjue** [comment]
hi @melissahermes99,

Hope all is well. 

I just wanted to confirm what you would like to see when the `Boundaries` area of the desktop menu gets expanded. 

A previous developer created a `CouncilSelector` component that looks like the area circled in red:

![image](https://user-images.githubusercontent.com/1448719/196345231-56f925e5-acb6-4f8c-bec9-2e1edcaa3c4a.png)

I'm wondering
- Would you like to see the `Type District Name` search filter?
- Do you think the sea green/cyan `Neighborhood District` heading should still appear since `Neighborhood Districts` already appears in the drop down menu at the top. It may appear redundant if we kept both.

If there is anything else you would like to see, please let me know. Looking forward to your response!

**Comment by edwinjue** [comment]
Hi @melissahermes99, it was great catching up with you last Wednesday. I hope you're well.

With what you're saying, are you suggesting the following for the `District` tab:
![image](https://user-images.githubusercontent.com/1448719/197117521-6512ffd8-774e-46f0-8578-7621182d4b63.png)

Which in words, replacing the current `Enter District` search input circled at the top with the `Boundaries` area circled below?

Otherwise, it is not clear what the Boundaries area at the bottom would do differently than the Search at the top. Let me know what you think. Thanks!

**Comment by melissahermes99** [comment]
I just spoke with Elizabeth and we haven't fully discussed what the menu would look like under the District tab. She believes it was for Business Districts, as opposed to Neighborhood Councils.  So it seems that the District tab and drop-down would serve the same purpose just with extra options. The dropdown could have NCs, Business Districts, etc. any kind of border distinctions as described by the section heading. I think that’s why a scroll was incorporated, to get to the other menu options. I've come up with some changes on Figma, let me know if these work for you!

![image](https://user-images.githubusercontent.com/97048386/197248798-e7ddf8b2-47ab-4171-a7c9-44ad7bd95025.png)

**Comment by edwinjue** [comment]
Hey @melissahermes99. Since I'm a late comer to the game, I'm still learning about the expectations the end users have and their requirements. I really appreciate your patience and your diligence. 

So, If I understand correctly, everything we're designing is under the "Address" tab and the "District" tab is something else in the works. Is this correct? 

Please feel free to correct me if I've misunderstood. Thanks!

**Comment by melissahermes99** [comment]
That's correct! I'm going to bring it up in the meeting today with Elizabeth and hopefully we can finalize what should go under that tab so we can finish up the menu.

**Comment by edwinjue** [comment]
Hi @melissahermes99 @elizabeth-ux thanks for dropping in tonight. 

Per our discussion, just wanted to let you know I was able to draft up a version of the frontend per your new design in [Figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1009%3A1004)

Please let me know how you think it looks. If there is anything you'd like me to change, please feel free to let me know:

### Default (Both collapsed)
![image](https://user-images.githubusercontent.com/1448719/198199374-06af5730-5b36-4b84-ad81-6f4fb0ed2d4b.png)

### Filters expanded
![image](https://user-images.githubusercontent.com/1448719/198199398-f029ba17-3836-4ba6-92a1-ffe02af36f94.png)

### Boundaries expanded
![image](https://user-images.githubusercontent.com/1448719/198199444-ab04a152-4d97-4bc3-b7fb-7fef67b96476.png)

**Comment by melissahermes99** [comment]
Wow! That looks fantastic, I'll pass this along to Elizabeth and we'll finalize if this is the way to go. Either way, it looks great and I'm super impressed with how fast you came up with this design!

**Comment by edwinjue** [comment]
Thanks, keep me updated!

**Comment by melissahermes99** [comment]
@edwinjue Could you give me more insight into the hamburger menu idea you and Adriana had brought up?  For the upcoming launch, we'll keep the menu you had created last week except we'll remove the tabs from the top and change the title. I've attached an image of what we were thinking. For the next version, we'll create some concepts and ideas for how we can place the menu and the search bars within the menu.
![image](https://user-images.githubusercontent.com/97048386/199541127-aee77457-a577-446d-b911-ee6350dc736f.png)

**Comment by mc759** [comment]
Hey @melissahermes99 Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by edwinjue** [comment]
Hi @mc759, this is on the engineering team's radar and is currently still a work in progress for H123. We will update this issue as soon as we have work to merge into dev
