### ISSUE TITLE
Render 311 requests as we receive them

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1408]
### Overview
Currently, by default, the frontend pulls request data by making 7 concurrent API calls, one for each day of the past week. We wait until all the calls complete to render the request data on the map.

To improve the user experience, we can render request data as it comes in; i.e., as soon as we get the data for a day, immediately render it.

### Action Items
- [ ] [here](https://github.com/hackforla/311-data/blob/dev/client/components/Map/index.js#L248) is where we block on all the responses. We should remove the `Promise.all` call and replace it with the appropriate code to render as soon as we get each day's worth of data.
- [ ] We'll also need to modify the way that we are updating the state in redux, which is the code [block](https://github.com/hackforla/311-data/blob/dev/client/components/Map/index.js#L253-L256) immediately following. We track two things in redux: the actual request data, and the date ranges which are covered by the request data. So these redux updates will need to be split into per-day calls as well.

**Comment by mc759** [comment]
Hey @hqasmei Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by hqasmei** [comment]
Hi @mc759 

Progress: Looked into and tried some possible solutions but nothings has worked so far. Talked to Nich and Edwin about a potential solution a few weeks back but ran into problems with implementing it. Still hasn't been resolved. Haven't worked on it since we started break.

Blocker: Not having too much background knowledge with backend and spending time understanding what the code is doing. I understand what it needs to do, but most of my time has been trying different suggestions from articles and stack overflow.  Also I'm not too familiar with Inheritance style React, more familiar with Composition based. So a little bit of a learning curve. Would probably be done quicker with someone more experienced in backend.

Availability: a couple hours a week (~6 hours), mainly evenings and weekends

ETA: Not sure, I'll take a look at it more tomorrow and get back to you
