### ISSUE TITLE
Address Search restrict typeahead to relevant locations

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1539]
### Overview
To improve user experience, display only relevant location in the Address Search typeahead.

For example, when searching 'nor' in the Address Search, "North Carolina" shouldn't be listed:
![image](https://github.com/hackforla/311-data/assets/1448719/5cf8072a-c3da-4f4b-b4ea-fb22a1992b0f)

**Comment by wmb1232** [comment]
Place for change is in components/Map/Control/mapSearch,jsx:80. when creating the MapboxGeocoder object we need to add a new option named filter with the following options
filter?: Function – A function which accepts a Feature in the Carmen GeoJSON  format to filter out results from the Geocoding API response before they are included in the suggestions list. Return true to keep the item, false otherwise.
