### ISSUE TITLE
Need to handle MultiPolygons in data/ncGeojson.js

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1540]
### Overview
Currently `ECHO PARK NC` and `NC VALLEY VILLAGE` are classified as `MultiPolygons` and won't zoom in when searched for in the Address Search. 

### More Info
We need to take a look at the logic in data/ncGeojson.js and find a way to determine when a given coordinate falls inside a  MultiPolygon boundary

### Action Items
- Outlined here: https://github.com/hackforla/311-data/issues/1540#issuecomment-2477485213

### Resources/Instructions
- [TurfJS](https://turfjs.org/)
- [booleanPointInPolygon](https://turfjs.org/docs/api/booleanPointInPolygon)

**Comment by ryanfchase** [comment]
@wmb1232 are you still working on this issue? If not, we will unassign

**Comment by bberhane** [comment]
@ryanfchase Not sure if anyone as worked on this since you last inquired

**Comment by ryanfchase** [comment]
@bberhane added `draft` and `needs more info`, attached it to the next Engineering meeting for team review

**Comment by kdow** [comment]
I found [this section of geoUtils.js](https://github.com/hackforla/311-data/blob/eee59bbf2de9f700db0305e4e158cb520ae4b15a/components/Map/geoUtils.js#L71-L83) that filters out the two `MultiPolygon`NCs (`ECHO PARK NC` and `NC VALLEY VILLAGE`) since they weren't working with `booleanPointInPolygon`. 

[`booleanPointInPolygon`](https://turfjs.org/docs/api/booleanPointInPolygon) can take a polygon or multipolygon, but the feature type needs to be specified. We can use a for loop with a conditional so we can use either  `polygon(feature.geometry.coordinates)`  or `multiPolygon(feature.geometry.coordinates)` with `booleanPointInPolygon`. 

I've pushed my code to this branch: https://github.com/hackforla/311-data/pull/1858

With the change I checked an address in Echo Park (1226 N Alvarado, Los Angeles, CA 90026), one in Valley Village (5000 Colfax Avenue, Valley Village, CA 91607), and one outside of either of those NCs, and they all zoomed in properly. (The addresses in Echo Park and Valley Village do not zoom in with the current codebase without this fix).

**Comment by ryanfchase** [comment]
@kdow's writeup provided the information we were looking for. PR that fixes the issue (https://github.com/hackforla/311-data/pull/1858) is approved. The ticket is now awaiting merge, no further info needed.
