### ISSUE TITLE
Workshop New Charts From MVP List

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1575]
### Overview
We are creating new charts based on discussion in PM meeting. New charts will be made to spec per our [MVP List](https://docs.google.com/document/d/1aQqAn_OOBZhpyHZcAklTqgdH8SDWAMmDep12v64k324/edit#bookmark=id.33fi5mlma6em)

We will make the following charts:
- Total Requests By Request Type
  - Bar Chart or Pie Chart
- Median Days to Close Tickets by request type
  - Bar Chart of Median
- Division of Fulfilling Requests
  - Pie Chart

### Action Items
- Create some data driven sketches via the observable platform
- Demonstrate that real Service Request data can be supplied to create the desired charts
- Consult with Design team to workshop the charts and arrive at an initial design

### Deliverables
- [ ] observable page with the 3 desired charts
- [ ] schedule handoff meeting with design team

**Comment by ryanfchase** [comment]
Moving this issue forward and closing #1505 since we are picking a different approach for Dashboard page.

**Comment by Ykaros** [comment]
After a discussion with Edwin, we came up with some thoughts regarding the visualization and layout. 

- Darken the surrounding area that cannot be interacted by users. 
- Position the city map to left side and leave more space for charts/graphs on the right side. 
- Add export feature to the visuals/search data, along with a minimize button for the visuals.
- Instead of putting visuals under dashboard, put more detailed insights into the data/some news there. 
- Zoom in/out?

**Comment by ryanfchase** [comment]
@Ykaros I believe this comment belongs in a ticket meant for the map visualization, not the dashboard page. I'm going to close this ticket since the work is done, and I will ping you with a ticket that this info should go on.
