### ISSUE TITLE
Update Privacy Policy

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1581]
### Overview
We need to update the contents of the privacy policy. See comments below for a visual representation of the changes.

### Action Items
- [x] Review the Privacy Policy's diff (see comment below, strikethrough means remove)
- [x] Make changes to the Privacy Policy page via the Contentful platform
- [ ] Have another PM review that the changes were propagated by checking [our github pages site's policy page](https://hackforla.github.io/311-data/#/privacy)

### Resources/Instructions
1. Log into Contentful (credentials found in 311-Data-Dev 1Password Vault). You will see the dashboard on successful login (see image below for reference).
2. Click on the Privacy Policy dashboard item
3. In Contentful's markdown editor, begin to make the requested changes to the content
4. When finished, hit publish changes

Ticket is done when the changes are published.

**Contentful Dashboard**
![image](https://github.com/hackforla/311-data/assets/6414668/6324fa02-84a4-46ba-add6-afebc8891d85)

**Privacy Policy Dashboard Item** (click this to edit the Privacy Policy page)
![image](https://github.com/hackforla/311-data/assets/6414668/61d01824-d0e9-4305-b9a2-a3ce83b47115)

**Privacy Policy Editing Page**
![image](https://github.com/hackforla/311-data/assets/6414668/9f550960-33a5-4a76-a703-54475e87cca3)

**Comment by ExperimentsInHonesty** [comment]
311-data.org is a nonprofit website run by Hack for LA which is a brigade of ~Code for America Labs~ **Civic Tech Structure**, Inc. ("~Code for America~**Civic Tech Structure**", "we", "us", "our"). This Privacy Policy describes how we collect, use, and protect your personal information on our websites (Sites), including the 311-Data Project Website ("311-data.org"), and our 311 Report Generator Website ("https://hackforla.github.io/311-report/") By submitting your personal information on our websites, you agree to the terms in this Privacy Policy. If you do not agree with these terms, please do not use our websites.

Overview
We collect information from you when you visit and take actions on our website. We use this information to provide the services you've requested.
We use cookies (such as those stored by Google Analytics) to provide a better experience and improve our website.
We will not knowingly disclose or sell your personal information to any third party, except as provided in this privacy policy.
Protecting your personal information is extremely important to us and we take all reasonable measures to do so.
The personal information we collect
Visiting 311-data.org
We automatically collect and store data about your visit to 311-data.org:
Domain from which you access the Internet
Operating system on your computer and information about the browser you used when visiting the site
Date and time of your visit
Pages you visited
Address of the website that connects you to the Site (such as google.com or bing.com)
The queries you make on our site. (E.G. last 6 months of data for bulky items)
None of the information we collect about you when you visit 311-data.org is personally identifiable unless you submit your contact information in the form on the Contact Us submit page.
We use this non personally identifiable information to understand how the 311-data.org website is used, to improve the website, and to monitor usage for security purposes.
We will not collect personal information from you without your knowledge and consent, except in a few limited circumstances as described in this policy.
Filling in Webforms such as Contact Us
We use github to process requests from our contact us page.
When you submit the contact us form, your personal data will be transferred to github and a ticket is created so someone from our team can get back to you.
The personal data we collect when you sign up to our mailing list includes:
Your name
Your email address
Domain from which you access the Internet
IP address
Operating system on your computer and information about the browser you used when visiting the site
Date and time when you submit the form
Address of the page on our website, or the third-party website that connected you to sign-up form
We use the collected email addresses of our contact us form to respond to people's requests. If you are interested in additional information about Hack for LA or ~Code for America~**Civic Tech Structure**, feel free to reach out.
We use the personal data we collect to understand how people ask us questions and to improve the experience of doing so.
Google Analytics
We use Google Analytics to understand how visitors use our site and to gather aggregate performance metrics.
We’ve set up Google Analytics so that it doesn’t collect your full IP address.
We don’t collect any personally identifiable information using Google Analytics, and we do not combine the information collected through Google Analytics with any personally identifiable information.
Google Analytics places a cookie on your web browser to identify you as a unique user. This cookie cannot be used by anyone but Google. Google's ability to use and share information collected by Google Analytics about your visits to this site is restricted by the [Google Analytics Terms of Use](http://www.google.com/analytics/terms/us.html) and the [Google Privacy Policy](http://www.google.com/policies/privacy/).
Cookies and other tracking technologies
Cookies are small text files that websites place on the computers and mobile devices of people who visit those websites. Pixel tags (also called web beacons) are small blocks of code placed on websites and emails.
We use cookies and other technologies like pixel tags to remember your preferences, enhance your online experience, and to gather data on how you use our Sites to improve the way we promote our content, programs, and events.
Your use of our Sites indicates your consent to such use of Cookies.
Third party service providers
We use third-party service providers to track and analyze statistical usage and volume information from our Site users. These third-party service providers use persistent Cookies to help us to improve the user experience, manage the content on our Sites, and analyze how users navigate and use the Sites.

Third-party service providers we use include Google Analytics, Mixpanel, Hotjar, Eventbrite, Donorbox, Medium, Twitter, Facebook, LinkedIn.

How to opt-out of the use of cookies
Most browsers are initially set up to accept HTTP cookies. If you want to restrict or block the cookies that are set by our Site, or any other site, you can do so through your browser setting. The ‘Help’ function in your browser should explain how. Alternatively, you can visit [www.aboutcookies.org](http://www.aboutcookies.org/), which contains comprehensive information on how to do this on a wide variety of browsers. You will find general information about cookies and details on how to delete cookies from your machine.

As required by law and similar disclosures
We may access, preserve, and disclose your information if we believe doing so is required or appropriate to:
comply with law enforcement requests and legal process, such as a court order or subpoena;
respond to your requests; or
protect your, our, or others’ rights, property, or safety
For the avoidance of doubt, the disclosure of your information may occur if you post any objectionable content on or through the Site.
Merger, sale, or other asset transfers
We may transfer your information to service providers, advisors, potential transactional partners, or other third parties in connection with the consideration, negotiation, or completion of a corporate transaction in which we are acquired by or merged with another company or we sell, liquidate, or transfer all or a portion of our assets. The use of your information following any of these events will be governed by the provisions of this Privacy Policy in effect at the time the applicable information was collected.

Consent
We may also disclose information from you or about you or your devices with your permission.

Children’s privacy
We do not knowingly collect, maintain, or use personal information from children under 13 years of age, and no part of our Site is directed to children.
If you learn that a child has provided us with personal information in violation of this Privacy Policy, then you may alert us at [info@codeforamerica.org](mailto:info@codeforamerica.org).
Security
We make reasonable efforts to protect your information by using physical and electronic safeguards designed to improve the security of the information we maintain. However, as our Services are hosted electronically, we can make no guarantees as to the security or privacy of your information.

Right to be forgotten and rectification
You may request that we delete your personal data at any time. Requests can be submitted to [privacy@codeforamerica.org](mailto:privacy@codeforamerica.org).
You may request that we make corrections to your personal data at any time. You may request that incomplete data be completed or that incorrect data be corrected. Requests can be submitted to [privacy@codeforamerica.org](mailto:privacy@codeforamerica.org).
Changes
We may change this Privacy Policy from time to time. Please check this page frequently for updates as your continued use of this site after any changes in this Privacy Policy will constitute your acceptance of the changes.

Effective Date
This version of the policy is effective July 29, 2019.

Questions
If you have any questions, comments, concerns, or complaints related to our websites, please contact us by email at [311-data@hackforla.org](mailto:311-data@hackforla.org), ~by phone at (415) 816-1286, or~by mail at:

Hack for LA 
~155 9th Street San Francisco, CA 94103~
**13428 Maxella Avenue, Unit 821
Marina Del Rey, CA 90292**

We will do our best to resolve the issue.

**Comment by ryanfchase** [comment]
See my comment below for an updated version of Bonnie's comment that includes the relevant markdown, as it appears on Contentful.

**Comment by ryanfchase** [comment]
311-data.org is a nonprofit website run by Hack for LA which is a brigade of ~Code for America Labs~ **Civic Tech Structure**, Inc. ("~Code for America~**Civic Tech Structure**", "we", "us", "our"). This Privacy Policy describes how we collect, use, and protect your personal information on our websites (Sites), including the 311-Data Project Website ("311-data.org"), and our 311 Report Generator Website ("https://hackforla.github.io/311-report/") By submitting your personal information on our websites, you agree to the terms in this Privacy Policy. If you do not agree with these terms, please do not use our websites.

## Overview
- We collect information from you when you visit and take actions on our website. We use this information to provide the services you've requested.
- We use cookies (such as those stored by Google Analytics) to provide a better experience and improve our website.
- We will not knowingly disclose or sell your personal information to any third party, except as provided in this privacy policy.
- Protecting your personal information is extremely important to us and we take all reasonable measures to do so.

## The personal information we collect

### Visiting 311-data.org
- We automatically collect and store data about your visit to 311-data.org:
  - Domain from which you access the Internet
  - Operating system on your computer and information about the browser you used when visiting the site
  - Date and time of your visit
  - Pages you visited
  - Address of the website that connects you to the Site (such as google.com or bing.com)
  - The queries you make on our site. (E.G. last 6 months of data for bulky items)
- None of the information we collect about you when you visit 311-data.org is personally identifiable unless you submit your contact information in the form on the Contact Us submit page.
- We use this non personally identifiable information to understand how the 311-data.org website is used, to improve the website, and to monitor usage for security purposes.
- We will not collect personal information from you without your knowledge and consent, except in a few limited circumstances as described in this policy.

### Filling in Webforms such as Contact Us
- We use github to process requests from our contact us page.
- When you submit the contact us form, your personal data will be transferred to github and a ticket is created so someone from our team can get back to you.
- The personal data we collect when you sign up to our mailing list includes:
  - Your name
  - Your email address
  - Domain from which you access the Internet
  - IP address
  - Operating system on your computer and information about the browser you used when visiting the site
  - Date and time when you submit the form
  - Address of the page on our website, or the third-party website that connected you to sign-up form
- We use the collected email addresses of our contact us form to respond to people's requests. If you are interested in additional information about Hack for LA or ~Code for America~**Civic Tech Structure**, feel free to reach out.
- We use the personal data we collect to understand how people ask us questions and to improve the experience of doing so.

### Google Analytics
- We use Google Analytics to understand how visitors use our site and to gather aggregate performance metrics.
- We’ve set up Google Analytics so that it doesn’t collect your full IP address.
- We don’t collect any personally identifiable information using Google Analytics, and we do not combine the information collected through Google Analytics with any personally identifiable information.
- Google Analytics places a cookie on your web browser to identify you as a unique user. This cookie cannot be used by anyone but Google. Google's ability to use and share information collected by Google Analytics about your visits to this site is restricted by the [Google Analytics Terms of Use](http://www.google.com/analytics/terms/us.html) and the [Google Privacy Policy](http://www.google.com/policies/privacy/).

### Cookies and other tracking technologies
- Cookies are small text files that websites place on the computers and mobile devices of people who visit those websites. Pixel tags (also called web beacons) are small blocks of code placed on websites and emails.
- We use cookies and other technologies like pixel tags to remember your preferences, enhance your online experience, and to gather data on how you use our Sites to improve the way we promote our content, programs, and events.
- Your use of our Sites indicates your consent to such use of Cookies.

### Third party service providers
We use third-party service providers to track and analyze statistical usage and volume information from our Site users. These third-party service providers use persistent Cookies to help us to improve the user experience, manage the content on our Sites, and analyze how users navigate and use the Sites.

Third-party service providers we use include Google Analytics, Mixpanel, Hotjar, Eventbrite, Donorbox, Medium, Twitter, Facebook, LinkedIn.

### How to opt-out of the use of cookies
Most browsers are initially set up to accept HTTP cookies. If you want to restrict or block the cookies that are set by our Site, or any other site, you can do so through your browser setting. The ‘Help’ function in your browser should explain how. Alternatively, you can visit [www.aboutcookies.org](http://www.aboutcookies.org/), which contains comprehensive information on how to do this on a wide variety of browsers. You will find general information about cookies and details on how to delete cookies from your machine.

### As required by law and similar disclosures
- We may access, preserve, and disclose your information if we believe doing so is required or appropriate to:
  - comply with law enforcement requests and legal process, such as a court order or subpoena;
  - respond to your requests; or
  - protect your, our, or others’ rights, property, or safety
- For the avoidance of doubt, the disclosure of your information may occur if you post any objectionable content on or through the Site.

### Merger, sale, or other asset transfers

We may transfer your information to service providers, advisors, potential transactional partners, or other third parties in connection with the consideration, negotiation, or completion of a corporate transaction in which we are acquired by or merged with another company or we sell, liquidate, or transfer all or a portion of our assets. The use of your information following any of these events will be governed by the provisions of this Privacy Policy in effect at the time the applicable information was collected.

### Consent
We may also disclose information from you or about you or your devices with your permission.

### Children’s privacy

- We do not knowingly collect, maintain, or use personal information from children under 13 years of age, and no part of our Site is directed to children.
- If you learn that a child has provided us with personal information in violation of this Privacy Policy, then you may alert us at ~info@codeforamerica.org~**311-data@hackforla.org**.

### Security

We make reasonable efforts to protect your information by using physical and electronic safeguards designed to improve the security of the information we maintain. However, as our Services are hosted electronically, we can make no guarantees as to the security or privacy of your information.

### Right to be forgotten and rectification

- You may request that we delete your personal data at any time. Requests can be submitted to ~privacy@codeforamerica.org~**privacy@hackforla.org**.
- You may request that we make corrections to your personal data at any time. You may request that incomplete data be completed or that incorrect data be corrected. Requests can be submitted to ~privacy@codeforamerica.org~**privacy@hackforla.org**.

### Changes

We may change this Privacy Policy from time to time. Please check this page frequently for updates as your continued use of this site after any changes in this Privacy Policy will constitute your acceptance of the changes.

### Effective Date
This version of the policy is effective July 29, 2019.

### Questions
If you have any questions, comments, concerns, or complaints related to our websites, please contact us by email at 311-data@hackforla.org, ~by phone at (415) 816-1286, or~by mail at:

Hack for LA 
~155 9th Street San Francisco, CA 94103~
**13428 Maxella Avenue, Unit 821
Marina Del Rey, CA 90292**

We will do our best to resolve the issue.

**Comment by bberhane** [comment]
Updated effective date to today's date as well.

**Comment by ryanfchase** [comment]
Reviewed in 11/16 meeting. Closing as done.
