### ISSUE TITLE
Clean up Open PRs

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1626]
### Overview
We have a long list of PRs that likely aren't being used anymore. We'll use this ticket to list, review, and handle each of those PRs.

### Action Items: Please review these lists

PRs by Author
- [x] #1641
- [x] A few [README PRs opened by Edwin](https://github.com/hackforla/311-data/pulls?q=is%3Aopen+is%3Apr+author%3Aedwinjue+Update+README) (I've approved the most complete one, but I saw there were merge conflicts)

PRs which affect archived directories (e.g. `server`)
- [x] https://github.com/hackforla/311-data/pull/1496
- [x] https://github.com/hackforla/311-data/pull/1479
- [x] https://github.com/hackforla/311-data/pull/1168
- [x] https://github.com/hackforla/311-data/pull/1226
- [x] https://github.com/hackforla/311-data/pull/1242

Generally Outdated
- [x] https://github.com/hackforla/311-data/pull/1431
- [x] https://github.com/hackforla/311-data/pull/1159

**Comment by Skydodle** [comment]
Regarding dependabot PRs:

I’ve had small experience with dependabots on my personal projects. It basically scans the repository periodically to see if there are dependencies that can be updated without breaking the app, which help with closing security vulnerabilities from outdated packages.
It’s generally safe to trust the ones that has a check mark (which means it built with the updated dependency and passed the build test without conflict).

The only ones we would have to investigate manually are the ones with x marks that failed the build tests. But dependabots usually provide pretty good logs for one to investigate and fix. The failed reason varies. The one I experienced was an npm package that was super outdated and no longer supported/maintained.

**Comment by Skydodle** [comment]
But also my experience is based on personal projects, which are relatively small compare to real world projects. I've read some devs pointed out that as the app grow larger the dependencybot conflicts would also increase since the number of dependencies would also most likely be growing.

Another suggestion is to just ignore them and keep all dependencies on current version so we can focus on other things. I would even delete those current dependabot PRs (since those PRs suggested dep versions maybe outdated later on). Then when we are ready to launch or scale, run the dependencybot and spend time dealing with them all at once. Not sure if this is for the best though.

**Comment by ryanfchase** [comment]
@Skydodle thanks.

There are 36 dependabot open PRs, and maybe 2/3s have green checkmarks. In lieu of having a test framework, it may be prudent to go through each one and test that it doesn't break the map. It will take longer, but we don't have a better way of confirming that it was a non-breaking change.

Alternatively, one could go and, on their own branch, implement the code change from each of the green checkmark dependabot PRs. This person would then test them all at once, and see if the map works as expected. If not, we'd have to go through and weed out the bad change.

Thoughts?

**Comment by ryanfchase** [comment]
Thank you @Skydodle - I've moved the ticket to Prioritized Backlog. Please assign yourself when you begin working, partial investigative info is still useful. Feel free to do as much as you can and report your findings and unassign.

**Comment by Skydodle** [comment]
Thanks @ryanfchase I will work on it in the next few days and post findings.

**Comment by Skydodle** [comment]
@ryanfchase can you/ someone open a sub- issue specifically for dealing with the current dependabots PRs?

I have some findings for short-term and long-term solution, and I want to post them under this new sub-issue for discussion. I don't want to clog up this current issue's board, as clearing the dependabot PRs is just one of many sub-stasks of this issue.

Let me know what you think.

**Comment by ryanfchase** [comment]
@Skydodle I've opened a new issue here: https://github.com/hackforla/311-data/issues/1641

We'll move the issue to Prioritized Backlog once you're satisfied with the strategy there. Please unassign yourself from this ticket (since you're soon to contribute to 1641). Also, feel free to open new issues on your own via the Blank Issue template. Assign to myself / @edwinjue for us to approve the issue.

**Comment by Skydodle** [comment]
@edwinjue @ryanfchase I reviewed the remaning PRs listed in this issue, all of them were requested to merge with the `dev` branch, and therefore has no effect on the current working branch `main` whether we merge them or not. Also these were very old change requests (late 2021 to early 2023) pertaining to the previous repo before we switch to front-end only, lots of them were for our old backend (which we no longer use) with python and terraform files changes.

My suggestion is to close them without merge since they have nothing to do with the current working repo. Please kindly advise if I'm good to proceed.

**Comment by ryanfchase** [comment]
Thank you @Skydodle -- we're good to close the PRs without merge! Thank you for reviewing them.

**Comment by Skydodle** [comment]
@edwinjue @ryanfchase 

This is entire issue is ready to be closed, please kindly review the details below:
- I've closed out the outdated PRs listed in my previous comment
- Moved on to review the 3 README PRs & took action as below:
   - #1548 : It correctly updated the clone directory to cd into --> **Reviewed, Approved with comment & Merged.**
   - #1563 : It correctly updated the demo site link --> **Reviewed, Approved with comment & Merged.**
   - #1552 : This PR has the exact same code change as #1548 above, which caused the merge conflict due to redudancy --> **Closed without merge** due to same issue already solved by #1548

Side-note: 
- The README overall still has some outdated information and needs to be consider for future tickets.

Let me know if I'm good to proceed and close this issue. =)

**Comment by ryanfchase** [comment]
Looking great @Skydodle -- this issue is good to close

**Comment by Skydodle** [comment]
@ryanfchase Thank you clarifying the review & closing workflow!
