### ISSUE TITLE
Satellite/Map View Toggle

### ISSUE THREAD

**Issue by henrywang7** [hackforla/311-data#164]
Add a function to switch view from satellite to map

**Comment by adamkendis** [comment]
Satellite/Map toggle has been implemented in #373 . Screenshot of the map controls below. I didn't use a toggle switch for the overlays because:

1. We have more than two overlays including NC boundaries.
2. It'll be easier to extend with additional overlays we choose to incorporate into the map.

I might try to restyle the control or build a custom one after we hit MVP requirements. Okay to close this issue?

<img width="270" alt="Screen Shot 2020-03-04 at 8 19 03 PM" src="https://user-images.githubusercontent.com/40484278/75947655-fc849580-5e55-11ea-8922-c5f8b400e2b4.png">

**Comment by johnr54321** [comment]
Closing since this has been implemented.
