### ISSUE TITLE
Update request types info button

### ISSUE THREAD

**Issue by rsschacht** [hackforla/311-data#1713]
### Overview
We need to update the **Request Types** info button within the **filters** section. 

The button currently displays a single word: "Info" instead of information on request types. Instead, there should be information on 311 request types, similar to how we display information for **date range**. 

After confirming the text, we also need to have consistent design + functionality between the two popovers. 

Visualization:
<details><summary>Click to view screenshots</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/65207072/fedfeafd-04de-4a0c-aede-255b5682d8b9)
![image](https://github.com/hackforla/311-data/assets/65207072/28b341f0-8263-4d7f-a120-e01931544db0)

</p>
</details> 

### Action Items

- [x] Decide on text to be displayed within the request types information section 

~Confirm text w/ design team and address any possible layout issues with the text (length, etc.)~ Converting this to a design ticket
~Update information window with text. Confirm consistency of design between request types and info sections including font, layout, size, shape design, etc.~
we'll convert this into an engineering ticket

**Comment by ryanfchase** [comment]
@rsschacht Thank you! I've thought about whether to keep everything as one ticket, or split it into different tickets. I'm leaning towards leaving this ticket exclusively for Research and to create blocked (Icebox) tickets for other teams, referencing this ticket as the dependency. 

For the case of this ticket, we can ask design if they'd like to create their own ticket once Research has supplied them with text. But for sure we should make a separate dev ticket.

Here's what I suggest and then we can move this out of drafts:
- one sentence Overview in form of "X for Y":  e.g. `In the Search and Filters modal, we need to add a useful description to the Request Types info button so that users understand what this control does`
- any info beyond the `### Overview` section will go into a `### More Info` section
- You can remove the `Milestone: Missing` label
- Migrate last 2 action steps onto the follow-up dev ticket.

cc @bberhane @cottonchristopher

**Comment by ryanfchase** [comment]
Let's close this ticket, since we are now making a design ticket to review our text and produce a design for hand off.

Proposed text:
```
The service request categories for this public dataset are maintained by Information Technologies Agency and may not reflect the categories available on MyLa311.lacity.org
```
