### ISSUE TITLE
Convert analysis script to SQL queries

### ISSUE THREAD

**Issue by gennaer** [hackforla/311-data#213]
### Overview
Currently, analysis scripts create pandas dataframes which won't scale for larger datasets. Refactor code to do a majority of the calculations in SQL

### Dependencies
#210 

### Action Items
- [ ] compute average time-to-complete for a NC for a given time range
- [ ] compute number of requests for a NC for a given time range

**Comment by ryanmswan** [comment]
Feature development ongoing concurrent with issue #210

**Comment by ExperimentsInHonesty** [comment]
@ryanmswan can you provide a few more details...
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ryanmswan** [comment]
1. At this point the issue is waiting on #210 to begin writing queries to perform operations in MySQL. These two issues will be somewhat interdependent.

2. Next step is to identify which optimized operations are best performed in the database instead of in Python. 

3. This will be an optimization step that will likely be completed after #210 is finished.

4. Best guess ETA is 3/14.

**Comment by joshuayhwu** [comment]
- compute average time-to-complete for a NC for a given time range

SELECT AVG(closedate-startdate)
FROM <Table name>
WHERE ncname = <ncparam> AND createdate >= <start_date param> AND closedate <= <closedate param>;

- compute number of requests for a NC for a given time range
SELECT COUNT(srnumber)
FROM <Table name>
WHERE ncname = <ncparam> AND createdate >= <start_date param> AND closedate <= <closedate param> ;


Todo:
- Consult Ryan for most updated tasks and cleaned data tables in DB
- Gather what the next steps

**Comment by joshuayhwu** [comment]
After consulting Ryan, this issue should be closed instead.
