### ISSUE TITLE
Display Errors when Loading/Displaying Data fails

### ISSUE THREAD

**Issue by brodly** [hackforla/311-data#264]
### Overview
Figure out a way to display errors on the UI. These would include errors when requesting data has failed, or data has failed to load.

### Action Items
- Location of errors
- Handling multiple errors at once
- Modal vs Bottom Bar?

**Comment by itsjoycelee** [comment]
@brodly please review loading error message below (screenshot). 

![image](https://user-images.githubusercontent.com/59002767/74867420-7c184d80-5309-11ea-86d4-0d1265f89ef7.png)

This message would pop-up and the user would need to go back to resubmit the request or refresh the tool. I took a stab at the messaging but let me know if you think this will suffice to cover the message that the errors are due to data loading and data retrieval issues or there should be a blanket error message for data related errors.

The component is available on our local component library - Desktop components frame on figma [here](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=0%3A1).

Also, from a development POV, what are your thoughts on having an option for users to report the error or get help on the issue (or do we have a backlog of errors we can view and fix bugs when errors occur)?

**Comment by brodly** [comment]
<img width="466" alt="Screen Shot 2020-03-14 at 4 49 02 PM" src="https://user-images.githubusercontent.com/29147758/76692430-c42e4580-6613-11ea-8318-8bb8c2291025.png">
