### ISSUE TITLE
Create terraform provisioning script for AWS

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#268]
### Overview
Create terraform script to provision necessary resources for running 311-data on cloud service provider

### Action Items
- [x] provision EC2 instance t2.micro free tier
- [ ] provision PostgreSQL instance free tier
- [x] perform setup of necessary packages for EC2 instance including Git
- [x] clone 311-data GitHub repository to EC2 instance
- [x] modify database connection string in settings.cfg to point to correct database credentials

### Resources/Instructions
[Terraform Documentation](https://www.terraform.io/docs/index.html)
[Joel Parker Henderson's Terraform Demo](https://github.com/joelparkerhenderson/demo_terraform_aws)

### Resume Items
Worked with AWS cloud computing services and Terraform to provision database and compute resources.

**Comment by raymonddeng99** [comment]
Could I be assigned this issue? I've automated DevOps scripts before and am interested in helping out.

**Comment by sellnat77** [comment]
Hey @raymonddeng99 
Joel has a central terrafrom file/folder and we are working on centralizing it to prevent destruction of other peoples projects

So for now, he has already terraformed some resources for us to get a head start but we will need to add more and actually maintain the terraform sections that relate to 311-data
Im going to close this since we have everything we need but we will need more offical stuff coming up and i can mention you on those tickets
