### ISSUE TITLE
[Service] Common Metadata endpoint

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#433]
# Description
This service will provide common metadata that is used by the frontend to drive filtering

## Endpoint
Check or uncheck the supported methods
Accepted methods
  - [x] GET
  - [ ] ~POST~

Path: ```server:port/metadata```

## Inputs
This endpoint requires no inputs

## Outputs
To allow the frontend to accurately display filters, the backend will query the db for common metadata

**Use JSON code flags to describe the json payload**
```json
{
    "lastPulled": "timestamp",
    "data": {
      "neighborhood_councils":[ "HISTORIC HIGHLAND PARK NC", "", ... ],
      "request_types":[ "Bulky Items", "", ... ]
    }
}
```
Relates to #428

**Comment by jmensch1** [comment]
I'll take a look at this one. I was thinking of adding the github sha to the metadata output so we can display that in the front end (#399)

**Comment by jmensch1** [comment]
hi @sellnat77, got a question for you when you have a minute.

I'm trying to figure out how to access the sha of the latest commit from a python script, so we can serve it up to the client. There's lots of ways to get the sha if you have access to the `.git` directory of your project. https://stackoverflow.com/questions/14989858/get-the-current-git-hash-in-a-python-script  

Problem is, the `.git` directory in our project never gets into the docker container, since we only copy the `/server` stuff into docker.  So I'm wondering, how are we gonna get the sha into the docker container?

I was looking at your workflow for publishing the backend image. Maybe there's a way we could inject the sha into the container as an environment variable? 

Thanks!

**Comment by sellnat77** [comment]
I was just gonna say, let's go with the publish backend image workflow and utilize a environment variable

Anything local will default to 'development' or 'local' and when we deploy we will just override that variable through the workflow

**Comment by jmensch1** [comment]
Ok cool, I just did a PR...seems like it should work but I don't really know how to test this.

**Comment by jmensch1** [comment]
Is there a way to do that for the frontend container too? I didn't see any environment variables in the workflow file

**Comment by sellnat77** [comment]
> Is there a way to do that for the frontend container too? I didn't see any environment variables in the workflow file

Since the frontend is still being deployed via gh-pages this is the spot to drop in env variables
https://github.com/hackforla/311-data/blob/dev/.github/workflows/Continuous_Delivery.yml#L32
The docker image is still kinda wonky so dont worry about the `publish-frontend-image` workflow for now

**Comment by jmensch1** [comment]
got it, thanks!
