### ISSUE TITLE
Fix React-router for live site

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#514]
Navigating to any front-end route adds an extra /311-data/ after the hash.

![Screen Shot 2020-04-07 at 6 13 12 PM](https://user-images.githubusercontent.com/40484278/78733878-8dd6a400-78fb-11ea-89da-05d014699916.png)

**Comment by jmensch1** [comment]
Looks like this is because we're using the `basename` option in React Router. We might be able to get rid of the option and and still keep the `/311-data` basename in our url by configuring the `gh-pages` deployment differently. There's apparently a `dest` option to deploy to subdirectories.

https://www.npmjs.com/package/gh-pages

So for the `npm run deploy` command we'd run a script that looks something like this:

```
ghpages.publish('dist', {
  dest: '311-data'
}, callback);
```

**Comment by adamkendis** [comment]
Hey @raymonddeng99 . I'm going to take over this ticket if that's cool. I think this is a relatively quick front end fix.
