### ISSUE TITLE
Connections to DB are still persisting

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#550]
**Describe the bug**
Some db operations are still persisting their connections. We have a limited pool of 20 connections so we need to make sure there arent any left over connections

**To Reproduce**
unsure

**Expected behavior**
Any call involving the database does `not` persist a connection

**Comment by jmensch1** [comment]
I'm thinking this might have to do with how we're using sqlalchemy. Right now we're creating the engine on every request, inside the DataService constructor. According to their docs, we should only really be creating the engine once -- 

"The Engine is intended to normally be a permanent fixture established up-front and maintained throughout the lifespan of an application. It is not intended to be created and disposed on a per-connection basis; it is instead a registry that maintains both a pool of connections as well as configurational information about the database and DBAPI in use, as well as some degree of internal caching of per-database resources."
https://docs.sqlalchemy.org/en/13/core/connections.html

We could try moving the engine into its own module and configuring it when the app starts, and then the DataService could just use that engine instead of creating a new one every time. But kinda hard to know if this would work since the bug seems to be intermittent.

**Comment by jmensch1** [comment]
I'm ready to say this is fixed. The number of database connections reported in heroku is consistently 4, which I assume is the number of workers running in Sanic server.
