### ISSUE TITLE
UI: Smaller Pins

### ISSUE THREAD

**Issue by danarchen** [hackforla/311-data#592]
## Description
The current pins being in used are too big when zoomed in on map. Pins are still displayed in cluster due to wrong sizing.  The pins need to be able  to resize/adjust as users zoom in and out of the map.

## Action Items

- [x] Research / Sketch ideas of pin designs

- [x] Mock up idea

- [ ] Provide new pin components 

## Resources

- TBD

**Comment by johnr54321** [comment]
![map-dots-02](https://user-images.githubusercontent.com/20999589/84349093-715d1f00-ab6b-11ea-8803-733f155eaad6.png)
![map-dots-03](https://user-images.githubusercontent.com/20999589/84349095-728e4c00-ab6b-11ea-9694-698e73022a5b.png)
![map-dots-01](https://user-images.githubusercontent.com/20999589/84349096-728e4c00-ab6b-11ea-90b7-1819926c3bea.png)

Images attached

**Comment by johnr54321** [comment]
I like them.  Let's see what Thomas thinks.

**Comment by johnr54321** [comment]
@thomisfrank @danarchen He loves the mockups!  Do you need any more information before we pass this on to the devs?

**Comment by danarchen** [comment]
Glad that Thomas liked the mockup! I don't think we need to add anything else, but if @adamkendis anyone else needs anything just let me know!

**Comment by johnr54321** [comment]
time to start dev work.  changing hands.

**Comment by johnr54321** [comment]
@tan-nate @adamkendis I'd make sure you've coordinated with all the other devs on this.  I think there may be potential for overlap on this one: https://github.com/hackforla/311-data/issues/740.  Please ref work already done by jake here: https://311-data.vercel.app/

**Comment by adamkendis** [comment]
@johnr54321 
Thanks for the heads up. This issue was discussed with Jake on 7/30. It seems very unlikely that we'll be able to integrate the new map before launch, so we're going to mimic the smaller pin functionality in Jake's demo as closely as possible in the existing app (for now). Shifting to the new map will a large undertaking.

**Comment by adamkendis** [comment]
I'll pick this up this weekend.

**Comment by adamkendis** [comment]
**Status**: Small circle pins rendering on the Leaflet map but render speed still isn't where I'd like it to be. ~5 sec for 25-30k pins, ~15-20 sec for 75k pins on local server. Pan/zoom performance is smooth. Working on an idea to improve perceived load time by progressively rendering subsets of pins split by request type. Rather than the map hanging for several seconds with all pins appearing at once, pins for each request type would appear on the map in sequence.
**ETA**: Hoping to get this up on dev this weekend but mid-next week is probably more realistic.

![small-pins-zoomed-out](https://user-images.githubusercontent.com/40484278/91504828-14782780-e883-11ea-82ae-69cd7ea71ccd.png)
![small-pins-zoomed-in](https://user-images.githubusercontent.com/40484278/91504833-15a95480-e883-11ea-8aed-1641a40cce90.png)

**Comment by adamkendis** [comment]
**Status:** Wasn't able to complete ticket this week. Popups for circle pins are now working though there is a layer ordering issue with the NC boundaries layer. Need to fix this and finish up performance improvements this week.

**Comment by adamkendis** [comment]
**Status:** 

**Layer ordering problem with small pins:** Made some progress on this. Fairly certain it's narrowed down to a z-index issue with the overlay panes. 

**Small pins performance:** Unfortunately, the attempted improvements this past week haven't had a significant impact and the leaflet map still isn't on par with the mapbox map (vercel demo) in terms of initial render and smooth zooming. I _think_ a big factor in the performance discrepancy is leaflet does not use webGL while the mapbox library on vercel does. Rendering the dots on html5 canvas in Leaflet was a huge performance boost but still not up to mapbox-gl.

**Misc:** A few small changes made to the map while working on this ticket. Reduced zoom level steps when using mousewheel/trackpad swipe to zoom in and out. This makes the zoom feel much smoother while still allowing larger zoom steps with the zoom control buttons or keyboard +/-. Tweaked the auto-panning/zooming when clicking on an NC. Instead of quickly snapping to the NC, the map more smoothly pans and zooms in. 

**Next steps:** I have lots of time to work on this over the next few days. 
 - Run the app through a React profiler to pinpoint what exactly is causing the large delay to render for large numbers of pins (25k+). I strongly suspect the problem is coming from React, not the leaflet.js library.
- Try to implement a pins layer that uses webGL. Considerations with this approach: a fallback renderer should be included for devices that don't support webGL.

**Comment by adamkendis** [comment]
**Status:** webGL layer is working and fast. I just need to fix an issue with jagged edges on the dots when zoomed far in and some code cleanup. ETA tomorrow if not completed by tonight's meeting.
