### ISSUE TITLE
Draft email for contact response

### ISSUE THREAD

**Issue by jmensch1** [hackforla/311-data#687]
## Description

When a user sends us feedback through the contact form, we can send them an email thanking them for the feedback. We just need to decide what it says -- i.e., the subject line and the body.

This is the info we'll have about the user (in case we want to include it in the email):
- first name
- last name 
- email 
- association 
- the message they sent us

## Action Items

- [ ] draft email for contact form response

**Comment by jmensch1** [comment]
hey @johnr54321, assigning this to you cuz I'm not sure who will handle it. The backend part of this is on the way.

**Comment by johnr54321** [comment]
[first name],

Thank you for contacting 311-data.org. A ticket has been created ([ticket number]) and an email has been sent to our support team.  Please be patient with our response time since we are all volunteers.

Below is the information that we received from you:
_First Name: [First Name]
Last Name: [Last Name]
Email: [email]
Association: [association]
Message: [message]_

Thanks again for your interest and we look forward to working with you.

If you have any questions, feel free to contact us at 311-data@hackforla.org

**Comment by johnr54321** [comment]
@jmensch1 Hopefully this should do it.  Please also send this to 311-data@hackforla.org.  Thanks.

**Comment by jmensch1** [comment]
Thanks John, will do. You'll see some emails regarding Sendgrid in the 311-data email today. That's just me setting up the account.
