### ISSUE TITLE
Combining the comparison tool to the map/data tool

### ISSUE THREAD

**Issue by danarchen** [hackforla/311-data#740]
## Description
For the new home/splash page to work, we would need to come up with a design where the tool has all there function in one place. 

Of course, we can keep it the way it is. But if we could combine it all together that be the ideal.
## Action Items

- [x] mock up

- [x] discuss

- [ ] iterate

- [ ] discuss with developer

## Resources
Jake's Prototype: https://311-data.vercel.app/

**Comment by johnr54321** [comment]
@kevindperez Thank you very much for putting this together. It definitely helped us arrive at where we needed to go. @jmensch1 Here are a few notes from our conversation:
- Move Map / Data selection from top of page to the bottom options.  Default is map.
- Chart options can be taken off the menu because now we will load them all (even when comparing)
- Need the ability to export map to image. Please leave charts etc. all options for export.
- Increasing Engagement for the average citizen making all functions fully interactive for time periods 3 months or less:
-   Use Jake's model for Address / NC / CC selection for area selection.  Allow for multi-selection.
-   No toggle for comparison necessary. If 2nd Area bar is blank, then no comparison
-   Time frame selection default is currently open issues.  Other options will remain the same.
-   No request type selection except on right (like Jake's tool)
-   Add prototype infobox in upper right corner.
- For cases 6 months and above:
-  Screen does not change from default without selecting an area.  Dots load in this case.
- Visualizing the comparison between two areas:  Highlight both areas and fade the remaining areas:
<img width="953" alt="NC Selection" src="https://user-images.githubusercontent.com/20999589/89005650-d99dc680-d2b9-11ea-9fbe-fb79cb960bbd.png">

**Comment by johnr54321** [comment]
Jake, if you need more visualizations of the above, please contact Kevin.  Otherwise, please include the above in your next iteration.

**Comment by johnr54321** [comment]
@kevindperez Under resources in the description, please add the figma model so we can reference it. Thanks!

**Comment by jmensch1** [comment]
hi @kevindperez, do you have a link to your mockup for this? I was looking around in figma but didn't see it. Thanks

**Comment by kevindperez** [comment]
@jmensch1 Heres the link: https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A2       
You can find what I currently have under the "Desktop Version" page and it'll be the last screens on the bottom under "New in Progress"

**Comment by johnr54321** [comment]
@jmensch1 Let us know if you need anything else.  Also just want to make sure you are aware of the work being done in #592 so you could coordinate with Nate on his piece.
