### ISSUE TITLE
Update social media share image with H4LA logo

### ISSUE THREAD

**Issue by pras4u** [hackforla/311-data#757]
Red square H4LA logo to find a place in the 311 rectangle image in social media share

**Comment by johnr54321** [comment]
When we put the link to our site up, needs to appear here.  @pras4u Can you find some samples that UX can use?

**Comment by danarchen** [comment]
Please see link for social media share image with H4LA logo.
I also added the empower LA logo, since we talked about it on Thursday. 

Let me know what you guys think @johnr54321  @pras4u 
I can also remove it or place it in the corner of the image if you do not like the current placement.

https://drive.google.com/file/d/1e_uxSHbenZfSAbx-S4c7D2Z80yeFgvRd/view?usp=sharing

**Comment by danarchen** [comment]
@johnr54321 here's another version 

https://drive.google.com/file/d/1YIKDgoBM9cYZoYYqSwcKDeW6hriYohLH/view?usp=sharing

**Comment by adamkendis** [comment]
Completed last week. Swapped out the social-media-card-image.png in production s3 bucket with the new image.
