### ISSUE TITLE
[FEAT] Cluster pins by NC at highest zoom levels

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#790]
### Overview
At the moment we are using pysupercluster to group pins as the user zooms in towards the lower zoom levels. The problem is that these clusters don't really mean anything. They are just showing groups of pins that don't correspond to any geographic boundary. It would be better to cluster pins by NC at the higher zoom levels and then once the user had zoomed in far enough where they were only looking at around 1 NC they would revert to the current clustering behavior.

### Action Items
Need to start by understanding the scope involved. Would likely need to get a file of the NC geometries and use that to calculate the centroids for each. Easy to do this with GeoPandas as an offline process. This could then be loaded as as file but probably should end up in the database at some point. We'd then want to query/cache aggregates for each NC. Might impact the caching logic.

### Resources/Instructions
https://geopandas.org/index.html

**Comment by jmensch1** [comment]
related to #791

**Comment by JRHutson** [comment]
@jmensch1 It looks like this could use the same logic that I added for the transition from tooltip on mouse-over to displaying all NC names. I think it's the "ZoomThresholdMet" state. If it needs to break at a different zoom level it would need a separate state.

Basically when zoomed out beyond a point you would want to switch the marker display to display a single marker for each NC with a count of markers within the NC. Googling, I'm seeing a lot of discussion of how to do this using the leaflet Marker Cluster. It seems like the PolygonOptions method might let you pass the polygon to cluster based on rather than leaflet defining them itself. I'm not seeing a clear example of it in usage though.

Another option that might be simpler would be to use a DivIcon for the polygons and just have a function that counts the number of requests currently being displayed for that NC. If we went in this direction, the state change would turn off the DivIcon and enable the individual markers.Since our points have the NC info associated with them, that seems like it could work. As @mattyweb suggested, calculating the center of the NC's could be done with geopandas and the nc-boundary-2019.json file in client/data. 

I'm back in town after taking a few days away in the mountains. Let me know if it would be helpful to connect this week and discuss further.

**Comment by jmensch1** [comment]
ok cool, thanks. Sounds like Matt figured out the geopandas part. This will be useful when we get to the frontend.

**Comment by mattyweb** [comment]
Keeping this open for the time being in case we reach a breaking point trying to show all the data points at the same time on the city map. There is likely a point where we may not be able to show them all and might need to do some aggregation to the region or neighborhood council level.

**Comment by mattyweb** [comment]
this is obsolete with new design
