### ISSUE TITLE
Identify v1 app issues (devs)

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#801]
# Description
This is a brain dump for any issues we've identified with the current app from the user's perspective. We'll compare notes with UI/UX on Thurs, 9/10. This will allow the team to design and develop v2 features that resolve v1 problems.

All devs are free to edit this ticket and add bullet points under Action Items.

## Action Items

- [ ] Too many clicks to view any data.
- [ ] Too many calls to action upon first loading map
- [ ] No data displays upon map load
- [ ] Menu takes up large portion of the page
- [ ] If menu is minimized, users cannot choose different request types or date ranges
- [ ] Heat map appears uniformly red if there are many data points
     - look into hot spot map vs heatmap
- [ ] NC selection may be an unnecessary filter. The inconveniences for the user of being presented with another menu for NC selection and not necessarily being able to view data upon tapping another NC may outweigh the benefit of being able to reduce the clutter of points on the screen, which are only less cluttered at a zoomed out level anyway
- [ ] There should be a link to file a 311 request from the map

**Comment by mattyweb** [comment]
1. Should homepage start with About page? It's a bit dull. Might want to start with something more flashy.
2. Map filter overlay/menu is covers 40% of the map. Clicks seem to center behind it. Maybe it should collapse when the user hits submit? Could there be a collapsed mode that still shows the highlights of the filters (e.g. date range, a few councils, a few request types)? It could then expand only when clicked.
3. Map filter on my (laptop) machine, "Submit" button is not visible. Below the fold.
4. Data Visualization tool seems awkward combined with the map. Feels like a standard reporting feature. Move it or combine with the Compare Different Councils feature?
5. Might be better to start with some data in the map rather than ask the user to make selections. Could we geolocate/auto-detect the user's NC?
6. How do users use the comparison reports? I don't understand comparing groups of NCs as opposed to individual ones. Or comparing NCs to City Councils. Maybe it'd be good to compare your NC to a city average? Or to similar council?
7. Do users understand what the dates represent? That these are the dates when issues are *reported*. Maybe there should be a 311 data FAQ explaining items.
8. Are the regions (groups of NCs) something users would be familiar with? E.g. Central 1, Central 2 seems confusing. Note that there is a different set of regions in the 311 data itself.
9. Missing Request Type: “Report Water Waste”
10. Possible to change colors on map clusters? Unclear what they represent. They might imply a relationship to the Request Types. Or that “green = good” when it’s just a comparatively low number of reports for the selected filters.
11. Not sure what the Request Type codes are for (e.g. EWT for E-Waste). Are users expected to be familiar with these already?
12. Not sure that colors are a great way to indicate Request Types since there are so many of them. Could we use icons instead? Or would that be too cute?
13. NC border highlights are the same color as the highways. Makes it hard to see the council boundaries.
14. "Data Updated Through" seems like it has a lot of attention.

**Comment by jmensch1** [comment]
Maybe instead of thinking of the app as two discrete categories -- the map and the visualizations -- we can think of it instead as a set of views on the underlying data. Some of them may involve a map, others might not. The views don't necessarily have to share a set of identical filters -- they can each have their own controls. We could just pick some of the coolest data-based UI's we can find and build them without worrying about whether they fit together. Here are some examples:

time sliders w/ map
http://bl.ocks.org/cmdoptesc/fc0e318ce7992bed7ca8
http://io.morphocode.com/urban-layers/ (hit "get started" after the loading indicator finished)

3-dimensional map
https://bl.ocks.org/Pessimistress/raw/1a4f3f5eb3b882ab4dd29f8ac122a7be/

steam graph for request types (instead of line/area charts)
https://www.d3-graph-gallery.com/streamgraph.html

**Comment by EchoProject** [comment]
Line items taken from above to work through and group together. 

- [ ] Heat map appears uniformly red if there are many data points (Why were other map types were taken away?)
   - look into hot spot map vs heatmap

UX
- [ ] Too many clicks to view any data. 
- [ ] Too many calls to action upon first loading map 
- [x] No data displays upon map load 
- [x] Menu takes up large portion of the page
- [ ] There should be a link to file a 311 request from the map (Add info to FAQ - requesting)
- [ ] If menu is minimized, users cannot choose different request types or date ranges (User story?) 

- [ ] NC selection may be an unnecessary filter. The inconveniences for the user of being presented with another menu for NC selection and not necessarily being able to view data upon tapping another NC may outweigh the benefit of being able to reduce the clutter of points on the screen, which are only less cluttered at a zoomed out level anyway 
- [ ] Should homepage start with About page? It's a bit dull. Might want to start with something more flashy.


Continue: 
- [ ] Map filter overlay/menu is covers 40% of the map. Clicks seem to center behind it. Maybe it should collapse when the user hits submit? Could there be a collapsed mode that still shows the highlights of the filters (e.g. date range, a few councils, a few request types)? It could then expand only when clicked.
- [ ] Map filter on my (laptop) machine, "Submit" button is not visible. Below the fold.
- [ ] Data Visualization tool seems awkward combined with the map. Feels like a standard reporting feature. Move it or combine with the Compare Different Councils feature?
- [ ] Might be better to start with some data in the map rather than ask the user to make selections. Could we geolocate/auto-detect the user's NC?
- [ ] How do users use the comparison reports? I don't understand comparing groups of NCs as opposed to individual ones. Or comparing NCs to City Councils. Maybe it'd be good to compare your NC to a city average? Or to similar council?
- [ ] Do users understand what the dates represent? That these are the dates when issues are *reported*. Maybe there should be a 311 data FAQ explaining items.
- [ ] Are the regions (groups of NCs) something users would be familiar with? E.g. Central 1, Central 2 seems confusing. Note that there is a different set of regions in the 311 data itself.
- [ ] Missing Request Type: “Report Water Waste”
- [ ] Possible to change colors on map clusters? Unclear what they represent. They might imply a relationship to the Request Types. Or that “green = good” when it’s just a comparatively low number of reports for the selected filters.
- [ ] Not sure what the Request Type codes are for (e.g. EWT for E-Waste). Are users expected to be familiar with these already?
- [ ] Not sure that colors are a great way to indicate Request Types since there are so many of them. Could we use icons instead? Or would that be too cute?
- [ ] NC border highlights are the same color as the highways. Makes it hard to see the council boundaries.
- [ ] "Data Updated Through" seems like it has a lot of attention.

**Comment by EchoProject** [comment]
@adamkendis will add notes to the check boxes.

**Comment by adamkendis** [comment]
I will add notes to the checkboxes on Saturday, 12/4.

**Comment by EchoProject** [comment]
Closing this issue as we're no longer working on v1.
