### ISSUE TITLE
Update NC Boundaries per City

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#807]
# Description
The department of Neighborhood Empowerment has updated boundaries that have not yet been translated to to some other departments.  In order to have the most updated NC Boundaries, we should update to the latest.

## Action Items
- Update our site to use the latest shape files.
- Test to ensure they don't break the site

## Resources
[New 2018 Maps files.zip](https://github.com/hackforla/311-data/files/5220351/New.2018.Maps.files.zip)
[Neighborhood_Council_Boundaries.gdb (2).zip](https://github.com/hackforla/311-data/files/5220352/Neighborhood_Council_Boundaries.gdb.2.zip)

**Comment by JRHutson** [comment]
@johnr54321 I was able to convert the gdb file to a geoJSON. There is a small bit up around Edwards AFB that it tied to the Sunland NC. Need to do some editing to delete it. Then I'll push a branch with the updated boundaries.

**Comment by adamkendis** [comment]
@jmensch1 
Updated NC boundaries included in this ticket. Any thoughts on how we should reconcile this with the data on the back end - maybe during nightly ingestion?

**Comment by jmensch1** [comment]
@adamkendis 
Hey, I'm not sure yet what kind of reconciliation will be necessary. If there aren't any changes to the NC id's we may not need to do anything on the backend. Let's discuss tonight.

**Comment by adamkendis** [comment]
@jmensch1 
Might not be able to make tonight's meeting - unsure yet. I think we'll need to update some NC ids or the NC boundaries displayed on the map will be at odds with the data. Here's an example:

**North Hollywood Northeast and NoHo NCs** 
Our site: southern boundary is Vanowen.
Updated boundary data: southern boundary is Victory (part of NoHo NC on our map).

See images below. It seems we'd need to change the NoHo requests falling between Victory and Vanowen to North Hollywood NE otherwise NoHo will display some requests that actually fall in North Hollywood NE.

### Updated North Hollywood NE boundary
<img width="837" alt="Screen Shot 2020-09-17 at 11 36 37 AM" src="https://user-images.githubusercontent.com/40484278/93513201-5f151e80-f8da-11ea-9191-8bc3447ceb3c.png">

### Requests for North Hollywood NE
![Screen Shot 2020-09-17 at 11 31 47 AM](https://user-images.githubusercontent.com/40484278/93513189-5cb2c480-f8da-11ea-8662-a9d74af93e8e.png)

### Requests for NoHo
![Screen Shot 2020-09-17 at 11 32 03 AM](https://user-images.githubusercontent.com/40484278/93513192-5d4b5b00-f8da-11ea-93d3-328020d2e79f.png)

**Comment by jmensch1** [comment]
Ok, yeah I see what you’re saying. So right now the backend doesn’t assign
NC ids to individual requests — the city assigns the ids to the requests
(in socrata) and we just assume that the city is correct. So i guess we’re
talking about adding a step to the nightly update that assigns NC ids based
on the new boundaries. Plus I guess we’ll need to recode the existing
requests in the DB to reflect the new boundaries.

I wonder if the city is planning to use the new boundaries in socrata. And
whether they plan to update the older requests in their own databases.

**Comment by adamkendis** [comment]
Yeah, exactly what you said. This would add a step to the nightly update to check if the NC id for each request we get from Socrata is valid based on the new boundary files we received and update them accordingly before storing in our db. I'm guessing this could significantly increase the time it takes for nightly update.

Hoping the same as you re the city updating their own data with current boundaries.

**Comment by JRHutson** [comment]
I would agree that the city updating their data would be the ideal. 

If that is not feasible currently and we wanted to update the data, it could be done with GeoPandas. We would need to decide how to handle the areas where there is overlap between NC's as well.

**Comment by mattyweb** [comment]
Did you guys discuss enabling GIS extensions for Postgres? If we did need to encode NCs from the service requests in bulk that'd probably be the fastest way to do it. Having geometries in the DB could open the door for other features in the app.

I also posted a bit about this in another ticket, but it becomes tricky if we can't treat these data sources as systems of record. It's hard to know what data needs to be changed because someone made a mistake (e.g. put the wrong boundary in) or because something changed (e.g. a new neighborhood council was created). Presumably those distinctions would determine which NC a hypothetical data point should be associated with.

Looking forward to checking out the new GeoJSON.

**Comment by jmensch1** [comment]
We haven't discussed GIS extensions for Postgres but I think it's a great idea and would probably open a bunch of doors. There's some code in ballotnav that might be helpful. https://github.com/hackforla/ballotnav/blob/master/backend/db/create-postgis-extension.sql

**Comment by mattyweb** [comment]
I did take a quick look at the new GeoJSON file and it doesn't look like it has the changes for the website file. The differences are pretty minor and I'm sure they can be handled manually, but the drift could get worse and worse over time. Would be good to have an idea on how frequently these files will be changing.

**Comment by JRHutson** [comment]
@jmensch1 What functionality are you thinking of opening up with PostGIS? It seems like Mapbox is opening up a lot of new options from what was in the demo you shared. Ex. Calculating the total of each category within a radius of the address entered. Are there things that mapbox won't support or are there interfaces where we wouldn't want to use mapbox?

**Comment by jmensch1** [comment]
So the only specific functionality I had in mind was a location-based
search in regards to "version 2". Like finding all requests within a
certain radius of the user's location. I imagine there's other cool stuff
we could do with it, seems like cool tech I just haven't explored it very
much.

**Comment by mattyweb** [comment]
Building on @jmensch1 here, what I'd really like to do as a user is set up an immediate area around me and "watch" it for new 311 calls. For instance, to get an alert whenever there's a new graffiti report on my block.

For me, and many people I suspect, the NC is still too big of an area. I live in DTLA but that doesn't mean I care about what's going on around the Staples Center which is 12 blocks from me. The NC is fine as an organizational unit and way to get the attention of the city, but I think in order to really engage people we're going to need to have some way of supporting smaller geographic units.

**Comment by jmensch1** [comment]
Ohh nice, that’s a great idea

**Comment by JRHutson** [comment]
I agree. 

If we don’t have user logins then there would have to be a way to unsubscribe. 

Has there been discussion of supporting user accounts?

**Comment by jmensch1** [comment]
Accounts have been mentioned but it’s always been pretty vague. I don’t
think we’ve ever had a clear picture of what kind of user-specific
functionality we want to provide.

**Comment by JRHutson** [comment]
@jmensch1 @mattyweb I'm going to open a separate issue for discussion of user notifications. I think there's a way it could be done.

**Comment by EchoProject** [comment]
Closing this issue because it was moved to the done column on 10-31-2020.
