### ISSUE TITLE
[Map] Show service request details in popup

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#947]
# Description

We need a popup displaying service request information when a map dot is clicked. We could show more information as well as some actions that the user could do (like link out to various places or share or bookmark the item).

## Action Items

- [x] Decide on the design (new designs were shown)
- [x] Decide what data points should be displayed
- [x] Decide if there should be additional features

**Comment by mattyweb** [comment]
This is the currently favored design:
![Iteration_5](https://user-images.githubusercontent.com/10199792/108664545-d6516e80-7487-11eb-897c-94d224f0042e.png)

**Comment by mattyweb** [comment]
Here is the data we have for the SR:
{
"requestId": 1174673,
"srnumber": "1-1584096961",
"councilId": 58,
"councilName": "Mid City West",
"typeId": 6,
"typeName": "Illegal Dumping",
"agencyId": 2,
"agencyName": "Sanitation Bureau",
"createdDate": "2020-03-25",
"closedDate": null,
"address": "8670 W BURTON WAY, 90048",
"latitude": 34.0720201513,
"longitude": -118.381076886
}

We could easily show this as well as any useful metadata about the types, councils, or agencies. For instance, how long it typically takes to close an issue of this type, the link to the council website or twitter, the links to the agency website or twitter.

**Comment by mattyweb** [comment]
- add agency
- break add median 'days to close' into separate ticket (
- break Zoom into separate ticket (@pras4u ) and remove from this design

**Comment by mattyweb** [comment]
@adamkendis the work looks great, but there were a few things from the discussion thread that were not resolved so I'm reopening. @kevindperez, can you help us out?

Here's a current example (from https://dev.311-data.org/map):
![image](https://user-images.githubusercontent.com/10199792/110974589-8857ba00-8313-11eb-82f9-1be2f81c2381.png)

The fields we are missing are:
1. Agency name: the city agency handling the request (e.g. Sanitation Bureau)
2. Source name: the way the request was made (e.g. Phone Call)

(My apologies that we didn't discuss source at the previous meeting. That was my oversight.)

A couple other thoughts:
- Could we treat the council name differently? It looks like it's part of the address. Maybe just more padding, parentheses, different color... I also don't think anyone is going to be familiar with the "NC" abbreviation. Maybe we just take that off.
- Since we're not doing medians or estimates or anything could we do something like show the number of days since the issue was created for open requests? Otherwise, people have to do math in their heads to figure out how long an issue has been open.

Something like:

**Status: Open (3 days)**

It's really coming together. Would be great to clean these things up so we can show it to the team next week!

**Comment by adamkendis** [comment]
@mattyweb 

Added agency (w/ link) and source to popup in #1049. Good ideas on tweaking the council styling and day count. I'll drop these quick changes in.
