### ISSUE TITLE
Allow for "link to service request" in URL

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#959]
# Description
Basically, it would be great to have a permanent link to a service request. Some URL that had the sr number in the query string for instance. This would let people bookmark service requests, email them, etc. We could also link to them from reports!

## Action Items
Build something in the client that would parse the SR number out of the query string and show it on the map. Would just center to the request with the popup displayed. Would likely need to work for any SR (even ones that were closed, etc.)

**Comment by danarchen** [comment]
Suggestion: add sr link to popup?

**Comment by danarchen** [comment]
@adamkendis has feasibility been evaluated?

**Comment by adamkendis** [comment]
@danarchen No design work is needed for this ticket. I've removed the UI/UX label.

**Comment by mattyweb** [comment]
@adamkendis, Was thinking about this a bit. It might be good to create the shareable links like this: 
https://dev.311-data.org/srnumber/1-1865751831

This would then pull up/redirect to the map with that request in the popup.

My thinking is:
1. That sharing by SR number makes sense since these are in the 311 system and are known to users
2. That we might want to show something other than the map in the future for these. Like we might create a request detail page with additional information that wouldn't fit in a popup.
3. We should expect these links to be shared in emails, Twitter, FB, etc. At some point we might want to use/create a URL shortener, but I think we're fine with this format for v2.

Any thoughts?

**Comment by adamkendis** [comment]
@mattyweb 

`That sharing by SR number makes sense since these are in the 311 system and are known to users`
`That we might want to show something other than the map in the future for these. Like we might create a request detail page with additional information that wouldn't fit in a popup.`

- Makes sense and sounds good to me.

`We should expect these links to be shared in emails, Twitter, FB, etc. At some point we might want to use/create a URL shortener, but I think we're fine with this format for v2.`

- I agree this format should be fine. 

I'll build this as laid out in your initial comment - going to 311-data.org/srnumber/1-1234567 will load the dot for that service request on the map and open the popup.

**Comment by EchoProject** [comment]
@adamkendis if this work hasn't been started yet, is there any objection to moving this issue into v3 scope?

**Comment by EchoProject** [comment]
Closing this issue after team discussion for lack of feasibility.
